# Generated by Django 4.0.3 on 2022-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
